### ISSUE TITLE
How can I add labels to stories?

### ISSUE THREAD

**Issue by ndbroadbent** [Masabi/clubhouse2-ruby#11]
Hello, thanks for this great gem!

Unfortunately I can't figure out how to add labels to a story via the API. I'm trying this:

```ruby
story.labels += [label]
```

But I get this error:

```
NoMethodError (undefined method `labels=' for #<Clubhouse::Story:0x00007fb0d4370780>)
```

Thanks!

**Comment by ndbroadbent** [comment]
I figured out that I could do:

```ruby
story.update(labels: [label, ...])
```

but there's actually a bug in the code and I get a `TypeError (class or module required)` error. 

[This StackOverflow answer explains how we need to wrap the class in parantheses](https://stackoverflow.com/a/23372852/304706) to fix the issue.

Opened a PR with a fix (#12) for that issue.

However, now I'm getting an infinite loop:

```
2.5.5 :026 > story.update(labels: [label])
Traceback (most recent call last):
       16: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `as_json'
       15: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `map'
       14: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `each'
       13: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `block in as_json'
       12: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:153:in `as_json'
       11: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:153:in `map'
       10: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:153:in `block in as_json'
        9: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:57:in `as_json'
        8: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `as_json'
        7: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `map'
        6: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `each'
        5: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `block in as_json'
        4: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:57:in `as_json'
        3: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `as_json'
        2: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `map'
        1: from /Users/me/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/core_ext/object/json.rb:172:in `each'
SystemStackError (stack level too deep)
```
